config/routes.rb
require 'sidekiq/web'

InchCI::Application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout

  namespace :api do
    get 'v1/cli' => 'cli#hint'
    post 'v1/cli' => 'cli#run'

    get 'v1/builds' => 'builds#hint'
    post 'v1/builds' => 'builds#run'

    get 'v2/builds' => 'builds#hint'
    post 'v2/builds' => 'builds#run'
  end

  # Help section
  get 'learn_more' => 'help#about', :as => :about
  get 'help' => 'help#index', :as => :help
  get 'lets_do_javascript' => 'help#javascript_beta', :as => :lets_do_javascript

  get 'help/webhook' => 'help#webhook', :as => :help_webhook
  get 'help/badge' => 'help#badge', :as => :help_badge
  get 'help/grades' => 'help#grades', :as => :help_grades
  get 'help/config_file_yaml' => 'help#config_file_yaml', :as => :help_configuration_yaml
  get 'help/config_file_json' => 'help#config_file_json', :as => :help_configuration_json

  # legacy URLs
  get 'howto/webhook' => 'help#webhook'
  get 'howto/config_file_yaml' => 'help#config_file_yaml'
  get 'howto/config_file_json' => 'help#config_file_json'

  root 'page#welcome'

  namespace :admin do
    get 'overview' => 'overview#index'
    get 'cli' => 'cli#index'
    get 'badges/added' => 'badges#added'
    get 'badges/in_readme' => 'badges#in_readme'

    resources :builds
    resources :projects
    resources :statistics do
      collection do
        get 'added_badges', :as => :added_badges
        get 'days', :as => :daily
        get 'weeks', :as => :weekly
        get 'months', :as => :monthly
      end
    end
    resources :users
  end

  duo    = ':service/:user'
  triple = ':service/:user/:repo'
  triple_constraints = {:service => /(github)/, :repo => /[^\/]+/}
  badge_constraints = {:format => /(png|svg)/}.merge(triple_constraints)
  json_constraints = {:format => /json/}.merge(triple_constraints)

  get "#{duo}" => 'users#show', :format => false
  post "init_projects" => 'users#init_projects', :as => :init_projects
  post "sync_projects" => 'users#sync_projects', :as => :sync_projects
  get "welcome" => 'users#welcome', :as => :welcome

  get "#{triple}/revision/:revision/code_object/:code_object" => 'code_objects#show', :constraints => triple_constraints

  get "#{triple}.:format" => 'projects#badge', :constraints => badge_constraints
  get "#{triple}.:format" => 'projects#show', :constraints => json_constraints

  get "(#{triple})/builds" => 'builds#index', :as => :builds, :constraints => triple_constraints
  #get "#{triple}(/revision/:revision)/list" => 'projects#show', :constraints => triple_constraints
  get "#{triple}(/revision/:revision)/suggestions" => 'projects#suggestions', :constraints => triple_constraints
  get "#{triple}(/revision/:revision)/history" => 'projects#history', :constraints => triple_constraints
  get "#{triple}(/revision/:revision)" => 'projects#show', :constraints => triple_constraints, :format => false

  post "#{triple}/rebuild" => 'projects#rebuild', :constraints => triple_constraints
  post "#{triple}/update_info" => 'projects#update_info', :constraints => triple_constraints
  post "#{triple}/create_hook" => 'projects#create_hook', :constraints => triple_constraints
  post "#{triple}/remove_hook" => 'projects#remove_hook', :constraints => triple_constraints

  get  "#{triple}/edit" => 'projects#edit', :constraints => triple_constraints
  put  "#{triple}" => 'projects#update', :constraints => triple_constraints

  post 'rebuild' => 'projects#rebuild_via_hook'

  resources :builds do
    member do
      get :history_show
    end
  end
  resources :projects

end

app/controllers/help_controller.rb
class HelpController < ApplicationController

  layout 'application'
end

app/helpers/help_helper.rb
module HelpHelper
end

app/views/help/_page.html.haml
- content_for(:subheader) do
  %h1= t('help.header.headline')

.row.row-content
  .container
    .help-wrapper
      = render "subnav"
      = yield

app/views/help/_subnav.html.haml
.col-lg-3.pull-right
  .help-navigation
    %strong Topics
    %ul.list-unstyled
      %li= link_to "Getting Started", help_path
      %li= link_to "The Grade System", help_grades_path
      %li= link_to "Using Badges", help_badge_path

    %strong Configuration
    %ul.list-unstyled
      %li= link_to "Using .inch.yml", help_configuration_yaml_path
      %li= link_to "Using inch.json", help_configuration_json_path
      %li= link_to "Webhooks", help_webhook_path

    %strong Inch on the web
    %ul.list-unstyled
      %li= link_to "Raising the visibility of inline-docs", "http://trivelop.de/2014/02/24/visibility-of-documentation/", :target => '_blank'
      %li= link_to "Why Inch doesn't use percentages", "http://trivelop.de/2014/02/17/why-inch-doesnot-use-percentages/", :target => '_blank'
    %strong Project pages
    %ul.list-unstyled
      %li= link_to "Inch project page", "http://trivelop.de/inch", :target => '_blank'
      %li= link_to "InchJS project page", "http://trivelop.de/inchjs", :target => '_blank'

app/views/help/about.html.haml
- content_for(:subheader) do
  %h2= t('about.headline')

.row.row-content
  .container
    = markdown t('about.abstract', :badge_image_url => image_path('badge-example.svg'))

    = render 'projects/form_new'

app/views/help/badge.html.haml
= render :layout => "page" do
  %h2= t('help.badge.headline')

  = markdown t('help.badge.body1')

  .text-center= image_tag('badge-explanation.png')

  = markdown t('help.badge.body2')

app/views/help/config_file_json.html.haml
= render :layout => "page" do
  %h2= t('help_configuration_json.headline')

  = markdown t('help_configuration_json.body1')

  %pre.code
    = preserve do
      :escaped
        {
          "files": {
            "included": [
              "plugins/**/*.js"
            ],
            "excluded": [
              "plugins/vendor/sparkr/sparkr.js",
              "plugins/vendor/**/*.js",
              "!regexp:/vendor/"
            ]
          }
        }
  = markdown t('help_configuration_json.body2')

app/views/help/config_file_yaml.haml
= render :layout => "page" do
  %h2= t('help_configuration_yaml.headline')

  = markdown t('help_configuration_yaml.body1')

  %pre.code
    = preserve do
      :escaped
        files:
          # define files included in the analysis (defaults to ["{app,lib}/**/*.rb"])
          included:
            - plugins/**/*.rb
          # define files excluded from the analysis (defaults to [])
          excluded:
            - plugins/vendor/sparkr/sparkr.rb

  = markdown t('help_configuration_yaml.body2')

app/views/help/grades.html.haml
= render :layout => "page" do
  %h2= t('help.grades.headline')

  = markdown t('help.grades.body')

app/views/help/index.html.haml
= render :layout => "page" do
  %h2= t('help.index.headline')

  = markdown t('help.index.abstract', :badge_image_url => image_path('badge-example.svg'))

app/views/help/javascript_beta.html.haml
- content_for(:subheader) do
  %h1 JavaScript on Inch CI

.row.row-content
  .container
    .promo-text
      :markdown
        ## Let's raise the visibility of documentation!

        The plan is for Inch CI to get JavaScript support in April. This might prove a challenge, since there aren't alot of structural similarities to Ruby and Elixir.

        This is where you come in:

        * To help me build the best Inch for JavaScript, ***<a href="https://github.com/inch-ci/inch_ci-web/edit/master/add_my_project_to_inch_ci.yml" style="text-decoration: underline">edit this list via GitHub</a>*** and add your project.
        * ***Tweet about it***, mentioning ["@InchCI for JavaScript"](https://twitter.com/InchCI), encouraging others to join in our quest to help make inline-docs better in JS.
        * By doing so, you are so-to-speak "joining the private beta of Inch CI for JavaScript". [1]
        * ***I will create a badge for you*** and evaluate your project with the InchJS release candidate.
        * You get access to these badges before the general public (as a "thank you").
        * We can discuss ***how to make the evaluation better/more fair***.

        That's the plan.

        ---

        ## What is this?

        Inch CI is a software project I created to help people document their code.
        It provides badges to show off inline-docs: [![Inline docs](http://inch-ci.org/github/FGRibreau/doxx.svg?branch=master)](http://inch-ci.org/github/FGRibreau/doxx)

        I really think that posting these badges in a project's README will benefit the project (because people can see that it's well documented) and the community by improving the visibility of documentation.

        ---

        ## Wait, who are you?

        I'm [@rrrene](https://twitter.com/rrrene), creator of [sparkr](http://trivelop.de/sparkr) and [Inch](http://trivelop.de/inch).

        If you have any questions or suggestions: I am [on Twitter](http://twitter.com/rrrene) and reachable via email (mail in [GitHub profile](https://github.com/rrrene)).

        ---

        <small>[1] Okay, technically you could always wait for the finished integration, but hey, think about what Open Source is all about: collaboration and community, getting the word out and being among the first to try new stuff.</small>

app/views/help/webhook.html.haml
= render :layout => "page" do
  %h2= t('help_webhook.headline')

  = markdown t('help_webhook.abstract')

  = markdown t('help_webhook.howto1')

  %p.help-image= image_tag "help-webhook/1-repo.png"

  = markdown t('help_webhook.howto2')

  %p.help-image= image_tag "help-webhook/2-settings.png"

  = markdown t('help_webhook.howto3')

  %p.help-image= image_tag "help-webhook/3-webhooks.png"

  = markdown t('help_webhook.howto4')

  %p.help-image= image_tag "help-webhook/4-add-webhook.png"

  = markdown t('help_webhook.howto5')

  %p.help-image= image_tag "help-webhook/5-done.png"