config/routes.rb
require 'sidekiq/web'

InchCI::Application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout

  namespace :api do
    get 'v1/cli' => 'cli#hint'
    post 'v1/cli' => 'cli#run'

    get 'v1/builds' => 'builds#hint'
    post 'v1/builds' => 'builds#run'

    get 'v2/builds' => 'builds#hint'
    post 'v2/builds' => 'builds#run'
  end

  # Help section
  get 'learn_more' => 'help#about', :as => :about
  get 'help' => 'help#index', :as => :help
  get 'lets_do_javascript' => 'help#javascript_beta', :as => :lets_do_javascript

  get 'help/webhook' => 'help#webhook', :as => :help_webhook
  get 'help/badge' => 'help#badge', :as => :help_badge
  get 'help/grades' => 'help#grades', :as => :help_grades
  get 'help/config_file_yaml' => 'help#config_file_yaml', :as => :help_configuration_yaml
  get 'help/config_file_json' => 'help#config_file_json', :as => :help_configuration_json

  # legacy URLs
  get 'howto/webhook' => 'help#webhook'
  get 'howto/config_file_yaml' => 'help#config_file_yaml'
  get 'howto/config_file_json' => 'help#config_file_json'

  root 'page#welcome'

  namespace :admin do
    get 'overview' => 'overview#index'
    get 'cli' => 'cli#index'
    get 'badges/added' => 'badges#added'
    get 'badges/in_readme' => 'badges#in_readme'

    resources :builds
    resources :projects
    resources :statistics do
      collection do
        get 'added_badges', :as => :added_badges
        get 'days', :as => :daily
        get 'weeks', :as => :weekly
        get 'months', :as => :monthly
      end
    end
    resources :users
  end

  duo    = ':service/:user'
  triple = ':service/:user/:repo'
  triple_constraints = {:service => /(github)/, :repo => /[^\/]+/}
  badge_constraints = {:format => /(png|svg)/}.merge(triple_constraints)
  json_constraints = {:format => /json/}.merge(triple_constraints)

  get "#{duo}" => 'users#show', :format => false
  post "init_projects" => 'users#init_projects', :as => :init_projects
  post "sync_projects" => 'users#sync_projects', :as => :sync_projects
  get "welcome" => 'users#welcome', :as => :welcome

  get "#{triple}/revision/:revision/code_object/:code_object" => 'code_objects#show', :constraints => triple_constraints

  get "#{triple}.:format" => 'projects#badge', :constraints => badge_constraints
  get "#{triple}.:format" => 'projects#show', :constraints => json_constraints

  get "(#{triple})/builds" => 'builds#index', :as => :builds, :constraints => triple_constraints
  #get "#{triple}(/revision/:revision)/list" => 'projects#show', :constraints => triple_constraints
  get "#{triple}(/revision/:revision)/suggestions" => 'projects#suggestions', :constraints => triple_constraints
  get "#{triple}(/revision/:revision)/history" => 'projects#history', :constraints => triple_constraints
  get "#{triple}(/revision/:revision)" => 'projects#show', :constraints => triple_constraints, :format => false

  post "#{triple}/rebuild" => 'projects#rebuild', :constraints => triple_constraints
  post "#{triple}/update_info" => 'projects#update_info', :constraints => triple_constraints
  post "#{triple}/create_hook" => 'projects#create_hook', :constraints => triple_constraints
  post "#{triple}/remove_hook" => 'projects#remove_hook', :constraints => triple_constraints

  get  "#{triple}/edit" => 'projects#edit', :constraints => triple_constraints
  put  "#{triple}" => 'projects#update', :constraints => triple_constraints

  post 'rebuild' => 'projects#rebuild_via_hook'

  resources :builds do
    member do
      get :history_show
    end
  end
  resources :projects

end

app/models/project.rb
require 'inch_ci/project_uid'

class Project < ActiveRecord::Base
  UID_FORMAT = /\A([a-z0-9\-\_\.]+)\:([a-z0-9\-\_\.]+)\/([a-z0-9\-\_\.]+)\Z/i

  has_many :branches, :dependent => :destroy
  has_many :code_objects, :dependent => :destroy

  belongs_to :default_branch, :class_name => 'Branch'

  has_many :builds, :through => :branches

  serialize :languages

  def self.find_by_uid(uid)
    uid = "github:#{uid}" if uid !~ /\:/
    where(:uid => uid).first
  end

  def user
    User.where(:provider => service_name, :user_name => user_name).first
  end

  # TODO: implement another way
  def service_name
    @service_name ||= InchCI::ProjectUID.new(uid).service
  end

  # TODO: implement another way
  def user_name
    @user_name ||= InchCI::ProjectUID.new(uid).user_name
  end

  # TODO: implement another way
  def repo_name
    @repo_name ||= InchCI::ProjectUID.new(uid).repo_name
  end

  validates :uid, :format => UID_FORMAT, :presence => true, :uniqueness => true
  validates :repo_url, :presence => true, :uniqueness => true
end

app/controllers/admin/projects_controller.rb
require 'inch_ci/controller'

class Admin::ProjectsController < ApplicationController
  include InchCI::Controller

  PROJECTS_PER_PAGE = 200
  LANGUAGE_NOT_SET = "LANGUAGE_NOT_SET"

  layout 'admin'

  def create
    action = Action::Project::Create.new(params, :admin)
    if action.success?
      redirect_to project_url(action.project, :pending_build => action.build_id)
    else
      expose action
      flash[:error] = t("projects.create.url_not_found")
      render :template => "page/welcome"
    end
  end

  def update
    @project = ::Project.find(params[:id])
    attributes = params[:project]
    @project.documentation_url = attributes[:documentation_url]
    @project.language = attributes[:language]
    InchCI::Store::SaveProject.call(@project)
    redirect_to admin_project_url(@project)
  end

  def index
    @projects = find_projects
    @languages = %w(Elixir JavaScript Ruby) + [LANGUAGE_NOT_SET]
  end

  def find_projects
    arel = filter_collection(Project).order('created_at DESC')
    @projects_total_count = arel.count
    arel.limit(PROJECTS_PER_PAGE)
  end

  def show
    @project = Project.find(params[:id])
  end

  private

  def filter_collection(arel)
    if params[:language].present?
      if params[:language] == LANGUAGE_NOT_SET
        arel = arel.where('language IS NULL')
      else
        arel = arel.where('LOWER(language) = ?', params[:language].to_s.downcase)
      end
    end
    if params[:fork].present?
      arel = arel.where(:fork => params[:fork] == '1')
    end
    if params[:badge_in_readme].present?
      arel = arel.where(:badge_in_readme => params[:badge_in_readme] == '1')
    end
    if params[:badge_generated].present?
      arel = arel.where(:badge_generated => params[:badge_generated] == '1')
    end
    if filled = params[:badge_filled_greater_than].presence
      arel = arel.where('badge_filled_in_percent >= ?', filled)
    end
    if params[:maintainers_with_badge_in_readme].present?
      projects = Project.where(:badge_in_readme => true)
      likes = projects.map do |project|
        "#{project.service_name}:#{project.user_name}/%"
      end.uniq
      conditions = (['uid LIKE ?'] * likes.size).join(' OR ')
      arel = arel.where(conditions, *likes)
    end
    if uid = params[:uid].presence
      arel = arel.where('uid LIKE ?', "%#{uid}%")
    end
    if params[:service]
      arel = filter_by_service_and_user(arel, params[:service], params[:user])
    end
    arel
  end

  def filter_by_service_and_user(arel, service, user_name)
    like = "#{service}:"
    if user_name
      like << "#{user_name}/"
    end
    arel.where('uid LIKE ?', like+'%')
  end
end

app/controllers/projects_controller.rb
require 'inch_ci/controller'
require 'inch_ci/badge'

class ProjectsController < ApplicationController
  include InchCI::Controller

  layout 'application'

  skip_before_action :verify_authenticity_token, :only => [:rebuild_via_hook]

  def badge
    action = Action::Project::Badge.new(params)
    if action.success?
      response.headers['Expires'] = Time.now.to_s
      response.headers['Pragma'] = 'no-cache'
      response.headers['Cache-Control'] = 'no-cache'
      send_file action.badge_filename, :content_type => action.content_type,
                                        :disposition => 'inline'
    else
      render :text => "Project or branch not found.", :layout => false, :status => 404
    end
  end

  def create
    action = Action::Project::Create.new(params, :homepage)
    if action.success?
      redirect_to project_url(action.project, :pending_build => action.build_id)
    else
      expose action
      flash[:error] = t("projects.create.url_not_found")
      render :template => "page/welcome"
    end
  end

  def create_hook
    action = Action::Project::ActivateHook.new(current_user, params)
    expose action
    if !action.success?
      flash[:error] = "Could not create hook for #{@project.name}"
    end
    redirect_to user_url(current_user, :tab => @project.language)
  end

  def edit
    process_project_action Action::Project::Show
  end

  def update
    action = Action::Project::Update.new(current_user, params)
    if action.success?
      redirect_to project_url(action.project)
    else
      redirect_to edit_project_url(action.project)
    end
  end

  def history
    process_project_action Action::Project::History
  end

  def rebuild
    action = Action::Project::Rebuild.new(params)
    if action.success?
      redirect_to project_url(action.project, action.branch.name, :pending_build => action.build_id)
    else
      render :text => "Project not found.", :layout => false, :status => 404
    end
  end

  def rebuild_via_hook
    action = Action::Project::RebuildViaHook.new(params)
    render :text => action.result
  end

  def remove_hook
    action = Action::Project::DeactivateHook.new(current_user, params)
    expose action
    if !action.success?
      flash[:error] = "Could not remove hook for #{@project.name}"
    end
    redirect_to user_url(current_user, :tab => @project.language)
  end

  def suggestions
    process_project_action Action::Project::Suggestions
  end

  def update_info
    action = Action::Project::UpdateInfo.new(current_user, params)
    redirect_to project_url(action.project, action.branch.name)
  end

  def show
    process_project_action Action::Project::Show
  end

  private

  def determine_layout
    case action_name
    when 'create'
      'cover'
    else
      'page'
    end
  end

  def process_project_action(action_class)
    action = action_class.new(params)
    expose action
    if action.project.nil?
      render :text => "Project not found.", :layout => true, :status => 404
    else
      if action.branch.nil?
        render :text => "Branch not found.", :layout => true, :status => 404
      end
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def badge_markup
    @badge_markup ||= BadgeMarkup.new(@project, @branch)
  end

  def escape_markdown(str)
    str.to_s.gsub('_', '\_')
  end

  def tweet_url(project = nil)
    url = project ? project_url(project) : root_url
    text = project ? t("shared.twitter_text", :project_language => project.language, :project_name => project.name) : t("shared.twitter_text_wo_project")
    "https://twitter.com/share?url=#{url}&text=#{text} &via=InchCI"
  end

  def github_issue_url(options = {})
    title = ''
    if project = options[:project]
      p_url = project_url(project)
      body = "\n\n---\nRe: [#{project.name}](#{p_url})"
      if code_object = options[:code_object]
        c_url = code_object_url(project, options[:branch].name, options[:revision].uid[0..7], :code_object => code_object)
        body = "\n\n---\nRe: [#{code_object.grade}] [#{code_object.fullname}](#{c_url}) in [#{project.name}](#{p_url})"
      end
    end
    "https://github.com/inch-ci/inch_ci-web/issues/new?title=#{URI.escape(title)}&body=#{URI.escape(body)}"
  end

  def link_to_build_history(project)
    url = project_build_history_path(project)
    link = link_to(t("projects.topbar.info.builds_link"), url)
    t("projects.topbar.info.builds_all", :link => link).html_safe
  end

  def link_to_edit_project(project)
    url = edit_project_path(project)
    link = link_to(t("projects.topbar.info.edit_link"), url)
    t("projects.topbar.info.edit_all", :link => link).html_safe
  end

  def link_to_project(project, text = project.name)
    link_to text, project_path(project)
  end

  def link_to_branch(branch)
    project = branch.project
    link_to truncate(branch.name), project_path(project, branch.name)
  end

  def link_to_revision(revision)
    branch = revision.branch
    project = branch.project
    link_to revision.uid[0..7], project_path(project, branch.name, revision.uid)
  end

  def link_to_subnavi(action, path, i18n_opts = {})
    text = t("projects.subnavi.#{action}", i18n_opts)
    classes = %w(btn btn-default)
    classes << 'active' if controller.action_name == action.to_s
    link_to text.html_safe, path, :class => classes
  end

  def link_to_with_hostname(url, options)
    hostname = URI.parse(url).host.gsub(/^www\./, '')
    link_to hostname, url, options
  end

  def promo_hint
    <<-PROMO
    <!--
Hi there,

I want to propose to add this badge to the README to show off inline-documentation: [![Inline docs](http://inch-ci.org/github/#{@project.name}.svg)](http://inch-ci.org/github/#{@project.name})

The badge links to [Inch CI](http://inch-ci.org) and shows an evaluation by [InchJS](http://trivelop.de/inchjs), a project that tries to raise the visibility of inline-docs. Besides testing and other coverage, documenting your code is often neglected although it is a very engaging part of Open Source.

So far over 500 **Ruby** projects are sporting these badges to raise awareness for the importance of inline-docs and to show potential contributors that they can expect a certain level of code documentation when they dive into your project's code and motivate them to eventually document their own. I would really like to do the same for the **JavaScript** community and roll out support for JS over the coming weeks (early adopters are [forever](https://github.com/foreverjs/forever), [node-sass](https://github.com/sass/node-sass) and [when](https://github.com/cujojs/when)).

Although this is "only" a passion project, I really would like to hear your thoughts, critique and suggestions. Your status page is http://inch-ci.org/github/#{@project.name}

What do you think?
    -->
    PROMO
  end

  def show_rebuild_link?
    @project.build_on_inch_ci?
  end
end

app/views/admin/projects/_form_new.html.haml
= form_tag(admin_projects_path, :method => :post, :class => 'form-inline') do
  .form-group{:class => flash[:error] ? 'has-error' : nil}
    = text_field_tag "repo_url", params[:repo_url], :class => "form-control", :placeholder => t("welcome.project_placeholder")
    = submit_tag t("welcome.add_project"), :class => "btn btn-default"
    - flash[:error].tap do |error_message|
      .error
        = error_message

app/views/admin/projects/_project.html.haml
.widget
  .widget-title
    = icon :calculator
    = "Project ##{project.id}"

.widget-body.medium.no-padding
  .table-responsive
    %table.table.table-striped.project
      %tbody
        %tr
          %th Project
          %td= link_to_project project
        %tr
          %th Language
          %td= link_to project.language, :language => project.language

        %tr
          %th Description
          %td= project.description

        %tr
          %th Origin
          %td= project.origin

        %tr
          %th Forked
          %td= project.fork

        %tr
          %th Hooked?
          %td= project.github_hook_active

        %tr
          %th Badge
          %td
            - if project.badge_generated
              = link_to_project project, image_tag(BadgeMarkup.new(project, project.default_branch).image_path(:svg))
              = "(#{project.badge_filled_in_percent}%)"
            - else
              &ndash;

        - if project.badge_generated
          %tr
            %th Badge in README
            %td
              - if project.badge_in_readme?
                %span.text-success= icon(:check)
              - else
                no

        - if project.badge_in_readme_added_at
          %tr
            %th Badge added
            %td= project.badge_in_readme_added_at

        - if project.badge_in_readme_removed_at
          %tr
            %th Badge removed
            %td= project.badge_in_readme_removed_at

        %tr
          %th Created
          %td= project.created_at

        %tr
          %th Homepage URL
          %td= project.homepage_url
        %tr
          %th Source Code URL
          %td= project.source_code_url
        %tr
          %th Repo URL
          %td= project.repo_url
        %tr
          %th Documentation URL
          %td= project.documentation_url

app/views/admin/projects/_table.html.haml
.table-responsive
  %table.table.projects
    %thead
      %tr
        %th #
        %th GitHub
        %th Origin
        %th Date added
        %th Language
        %th Builds
        %th Docs
        %th
        %th
    %tbody
      - projects.each do |project|
        - if project.default_branch
          %tr{:class => created_at_classes(project)}
            %td= link_to(project.id, admin_project_path(project.id))
            %td= link_to(project.name, project.source_code_url, :target => '_blank', :class => 'external')
            %td= project.origin
            %td= project.created_at.strftime('%Y-%m-%d')
            %td= link_to project.language || '-', :language => project.language
            %td= link_to icon(:signal), admin_builds_path(:service => project.service_name, :user => project.user_name, :repo => project.repo_name)
            %td
              - if project.documentation_url
                = link_to icon(:globe), project.documentation_url, :target => '_blank'
            %td.text-right
              - if project.badge_generated?
                - if project.badge_in_readme?
                  %span.text-success= icon(:check)
                = link_to_project project, image_tag(BadgeMarkup.new(project, project.default_branch).image_path(:svg))
            %td.text-right
              = link_to icon(:refresh), project_rebuild_path(project), :method => :post

app/views/admin/projects/index.html.haml
.col-lg-10
  .widget
    .widget-title
      = icon :database
      Latest projects

    .widget-body
      = render 'table', :projects => @projects

.col-lg-2
  .widget
    .widget-title
      = icon :filter
      Filters

    .widget-body
      = form_tag(params, :method => :get) do
        .form-group
          = label_tag :language, "Language"
          = select_tag(:language, options_for_select(['', *@languages], params[:language]), :class => 'form-control')

        .form-group
          = label_tag :badge_filled_greater_than, "Only badges filled more than"
          = select_tag(:badge_filled_greater_than, options_for_select(['', 0, 25, 50, 75], params[:badge_filled_greater_than]), :class => 'form-control')

        .form-group
          = label_tag :badge_generated, "Badge status"
          = select_tag(:badge_generated, options_for_select([[''], ['Badge generated', '1'], ['No badge generated', '0']], params[:badge_generated]), :class => 'form-control')

        .form-group
          = label_tag :badge_in_readme, "README status"
          = select_tag(:badge_in_readme, options_for_select([[''], ['Badge in README', '1'], ['No badge in README', '0']], params[:badge_in_readme]), :class => 'form-control')

        .form-group
          %label Limit to ...
          %label
            = check_box_tag :fork, '0', !!params[:fork]
            = "non-forked projects"

          %label
            = check_box_tag :maintainers_with_badge_in_readme, '1', !!params[:maintainers_with_badge_in_readme]
            = "users sporting badges"

        = submit_tag "Show projects"
        - if params.size > 2
          or
          = link_to "clear filters", admin_projects_path

    .widget-title
      = icon :search
      Search

    .widget-body
      = form_tag(params, :method => :get) do
        .form-group
          = text_field_tag :uid, params[:uid], :class => 'form-control'

        = submit_tag "Search"

    .widget-title
      Displaying
      = @projects.size
      = "/"
      = @projects_total_count
      projects.

app/views/admin/projects/show.html.haml
.row
  .col-lg-6
    = render "admin/projects/project", :project => @project

  .col-lg-4
    = form_for(@project, :url => admin_project_path(@project), :method => :put, :html => {:class => 'edit-project-form form-horizontal'}) do |f|
      .form-group{:class => flash[:error] ? 'has-error' : nil}
        = f.label(:language, t(".label.language"))
        = f.select(:language, InchCI::Config::LANGUAGES, {}, :class => "form-control")
      .form-group{:class => flash[:error] ? 'has-error' : nil}
        = f.label(:language, t(".label.documentation_url"))
        = f.text_field(:documentation_url, :class => "form-control")

      .form-group{:class => flash[:error] ? 'has-error' : nil}
        = submit_tag "Update project", :class => "btn btn-success"

        - flash[:error].tap do |error_message|
          .error
            = error_message