config/routes.rb
require 'sidekiq/web'

InchCI::Application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout

  namespace :api do
    get 'v1/cli' => 'cli#hint'
    post 'v1/cli' => 'cli#run'

    get 'v1/builds' => 'builds#hint'
    post 'v1/builds' => 'builds#run'

    get 'v2/builds' => 'builds#hint'
    post 'v2/builds' => 'builds#run'
  end

  # Help section
  get 'learn_more' => 'help#about', :as => :about
  get 'help' => 'help#index', :as => :help
  get 'lets_do_javascript' => 'help#javascript_beta', :as => :lets_do_javascript

  get 'help/webhook' => 'help#webhook', :as => :help_webhook
  get 'help/badge' => 'help#badge', :as => :help_badge
  get 'help/grades' => 'help#grades', :as => :help_grades
  get 'help/config_file_yaml' => 'help#config_file_yaml', :as => :help_configuration_yaml
  get 'help/config_file_json' => 'help#config_file_json', :as => :help_configuration_json

  # legacy URLs
  get 'howto/webhook' => 'help#webhook'
  get 'howto/config_file_yaml' => 'help#config_file_yaml'
  get 'howto/config_file_json' => 'help#config_file_json'

  root 'page#welcome'

  namespace :admin do
    get 'overview' => 'overview#index'
    get 'cli' => 'cli#index'
    get 'badges/added' => 'badges#added'
    get 'badges/in_readme' => 'badges#in_readme'

    resources :builds
    resources :projects
    resources :statistics do
      collection do
        get 'added_badges', :as => :added_badges
        get 'days', :as => :daily
        get 'weeks', :as => :weekly
        get 'months', :as => :monthly
      end
    end
    resources :users
  end

  duo    = ':service/:user'
  triple = ':service/:user/:repo'
  triple_constraints = {:service => /(github)/, :repo => /[^\/]+/}
  badge_constraints = {:format => /(png|svg)/}.merge(triple_constraints)
  json_constraints = {:format => /json/}.merge(triple_constraints)

  get "#{duo}" => 'users#show', :format => false
  post "init_projects" => 'users#init_projects', :as => :init_projects
  post "sync_projects" => 'users#sync_projects', :as => :sync_projects
  get "welcome" => 'users#welcome', :as => :welcome

  get "#{triple}/revision/:revision/code_object/:code_object" => 'code_objects#show', :constraints => triple_constraints

  get "#{triple}.:format" => 'projects#badge', :constraints => badge_constraints
  get "#{triple}.:format" => 'projects#show', :constraints => json_constraints

  get "(#{triple})/builds" => 'builds#index', :as => :builds, :constraints => triple_constraints
  #get "#{triple}(/revision/:revision)/list" => 'projects#show', :constraints => triple_constraints
  get "#{triple}(/revision/:revision)/suggestions" => 'projects#suggestions', :constraints => triple_constraints
  get "#{triple}(/revision/:revision)/history" => 'projects#history', :constraints => triple_constraints
  get "#{triple}(/revision/:revision)" => 'projects#show', :constraints => triple_constraints, :format => false

  post "#{triple}/rebuild" => 'projects#rebuild', :constraints => triple_constraints
  post "#{triple}/update_info" => 'projects#update_info', :constraints => triple_constraints
  post "#{triple}/create_hook" => 'projects#create_hook', :constraints => triple_constraints
  post "#{triple}/remove_hook" => 'projects#remove_hook', :constraints => triple_constraints

  get  "#{triple}/edit" => 'projects#edit', :constraints => triple_constraints
  put  "#{triple}" => 'projects#update', :constraints => triple_constraints

  post 'rebuild' => 'projects#rebuild_via_hook'

  resources :builds do
    member do
      get :history_show
    end
  end
  resources :projects

end

app/models/project.rb
require 'inch_ci/project_uid'

class Project < ActiveRecord::Base
  UID_FORMAT = /\A([a-z0-9\-\_\.]+)\:([a-z0-9\-\_\.]+)\/([a-z0-9\-\_\.]+)\Z/i

  has_many :branches, :dependent => :destroy
  has_many :code_objects, :dependent => :destroy

  belongs_to :default_branch, :class_name => 'Branch'

  has_many :builds, :through => :branches

  serialize :languages

  def self.find_by_uid(uid)
    uid = "github:#{uid}" if uid !~ /\:/
    where(:uid => uid).first
  end

  def user
    User.where(:provider => service_name, :user_name => user_name).first
  end

  # TODO: implement another way
  def service_name
    @service_name ||= InchCI::ProjectUID.new(uid).service
  end

  # TODO: implement another way
  def user_name
    @user_name ||= InchCI::ProjectUID.new(uid).user_name
  end

  # TODO: implement another way
  def repo_name
    @repo_name ||= InchCI::ProjectUID.new(uid).repo_name
  end

  validates :uid, :format => UID_FORMAT, :presence => true, :uniqueness => true
  validates :repo_url, :presence => true, :uniqueness => true
end

app/controllers/admin/projects_controller.rb
require 'inch_ci/controller'

class Admin::ProjectsController < ApplicationController
  include InchCI::Controller

  PROJECTS_PER_PAGE = 200
  LANGUAGE_NOT_SET = "LANGUAGE_NOT_SET"

  layout 'admin'

  def create
    action = Action::Project::Create.new(params, :admin)
    if action.success?
      redirect_to project_url(action.project, :pending_build => action.build_id)
    else
      expose action
      flash[:error] = t("projects.create.url_not_found")
      render :template => "page/welcome"
    end
  end

  def update
    @project = ::Project.find(params[:id])
    attributes = params[:project]
    @project.documentation_url = attributes[:documentation_url]
    @project.language = attributes[:language]
    InchCI::Store::SaveProject.call(@project)
    redirect_to admin_project_url(@project)
  end

  def index
    @projects = find_projects
    @languages = %w(Elixir JavaScript Ruby) + [LANGUAGE_NOT_SET]
  end

  def find_projects
    arel = filter_collection(Project).order('created_at DESC')
    @projects_total_count = arel.count
    arel.limit(PROJECTS_PER_PAGE)
  end

  def show
    @project = Project.find(params[:id])
  end

  private

  def filter_collection(arel)
    if params[:language].present?
      if params[:language] == LANGUAGE_NOT_SET
        arel = arel.where('language IS NULL')
      else
        arel = arel.where('LOWER(language) = ?', params[:language].to_s.downcase)
      end
    end
    if params[:fork].present?
      arel = arel.where(:fork => params[:fork] == '1')
    end
    if params[:badge_in_readme].present?
      arel = arel.where(:badge_in_readme => params[:badge_in_readme] == '1')
    end
    if params[:badge_generated].present?
      arel = arel.where(:badge_generated => params[:badge_generated] == '1')
    end
    if filled = params[:badge_filled_greater_than].presence
      arel = arel.where('badge_filled_in_percent >= ?', filled)
    end
    if params[:maintainers_with_badge_in_readme].present?
      projects = Project.where(:badge_in_readme => true)
      likes = projects.map do |project|
        "#{project.service_name}:#{project.user_name}/%"
      end.uniq
      conditions = (['uid LIKE ?'] * likes.size).join(' OR ')
      arel = arel.where(conditions, *likes)
    end
    if uid = params[:uid].presence
      arel = arel.where('uid LIKE ?', "%#{uid}%")
    end
    if params[:service]
      arel = filter_by_service_and_user(arel, params[:service], params[:user])
    end
    arel
  end

  def filter_by_service_and_user(arel, service, user_name)
    like = "#{service}:"
    if user_name
      like << "#{user_name}/"
    end
    arel.where('uid LIKE ?', like+'%')
  end
end

app/controllers/projects_controller.rb
require 'inch_ci/controller'
require 'inch_ci/badge'

class ProjectsController < ApplicationController
  include InchCI::Controller

  layout 'application'

  skip_before_action :verify_authenticity_token, :only => [:rebuild_via_hook]

  def badge
    action = Action::Project::Badge.new(params)
    if action.success?
      response.headers['Expires'] = Time.now.to_s
      response.headers['Pragma'] = 'no-cache'
      response.headers['Cache-Control'] = 'no-cache'
      send_file action.badge_filename, :content_type => action.content_type,
                                        :disposition => 'inline'
    else
      render :text => "Project or branch not found.", :layout => false, :status => 404
    end
  end

  def create
    action = Action::Project::Create.new(params, :homepage)
    if action.success?
      redirect_to project_url(action.project, :pending_build => action.build_id)
    else
      expose action
      flash[:error] = t("projects.create.url_not_found")
      render :template => "page/welcome"
    end
  end

  def create_hook
    action = Action::Project::ActivateHook.new(current_user, params)
    expose action
    if !action.success?
      flash[:error] = "Could not create hook for #{@project.name}"
    end
    redirect_to user_url(current_user, :tab => @project.language)
  end

  def edit
    process_project_action Action::Project::Show
  end

  def update
    action = Action::Project::Update.new(current_user, params)
    if action.success?
      redirect_to project_url(action.project)
    else
      redirect_to edit_project_url(action.project)
    end
  end

  def history
    process_project_action Action::Project::History
  end

  def rebuild
    action = Action::Project::Rebuild.new(params)
    if action.success?
      redirect_to project_url(action.project, action.branch.name, :pending_build => action.build_id)
    else
      render :text => "Project not found.", :layout => false, :status => 404
    end
  end

  def rebuild_via_hook
    action = Action::Project::RebuildViaHook.new(params)
    render :text => action.result
  end

  def remove_hook
    action = Action::Project::DeactivateHook.new(current_user, params)
    expose action
    if !action.success?
      flash[:error] = "Could not remove hook for #{@project.name}"
    end
    redirect_to user_url(current_user, :tab => @project.language)
  end

  def suggestions
    process_project_action Action::Project::Suggestions
  end

  def update_info
    action = Action::Project::UpdateInfo.new(current_user, params)
    redirect_to project_url(action.project, action.branch.name)
  end

  def show
    process_project_action Action::Project::Show
  end

  private

  def determine_layout
    case action_name
    when 'create'
      'cover'
    else
      'page'
    end
  end

  def process_project_action(action_class)
    action = action_class.new(params)
    expose action
    if action.project.nil?
      render :text => "Project not found.", :layout => true, :status => 404
    else
      if action.branch.nil?
        render :text => "Branch not found.", :layout => true, :status => 404
      end
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def badge_markup
    @badge_markup ||= BadgeMarkup.new(@project, @branch)
  end

  def escape_markdown(str)
    str.to_s.gsub('_', '\_')
  end

  def tweet_url(project = nil)
    url = project ? project_url(project) : root_url
    text = project ? t("shared.twitter_text", :project_language => project.language, :project_name => project.name) : t("shared.twitter_text_wo_project")
    "https://twitter.com/share?url=#{url}&text=#{text} &via=InchCI"
  end

  def github_issue_url(options = {})
    title = ''
    if project = options[:project]
      p_url = project_url(project)
      body = "\n\n---\nRe: [#{project.name}](#{p_url})"
      if code_object = options[:code_object]
        c_url = code_object_url(project, options[:branch].name, options[:revision].uid[0..7], :code_object => code_object)
        body = "\n\n---\nRe: [#{code_object.grade}] [#{code_object.fullname}](#{c_url}) in [#{project.name}](#{p_url})"
      end
    end
    "https://github.com/inch-ci/inch_ci-web/issues/new?title=#{URI.escape(title)}&body=#{URI.escape(body)}"
  end

  def link_to_build_history(project)
    url = project_build_history_path(project)
    link = link_to(t("projects.topbar.info.builds_link"), url)
    t("projects.topbar.info.builds_all", :link => link).html_safe
  end

  def link_to_edit_project(project)
    url = edit_project_path(project)
    link = link_to(t("projects.topbar.info.edit_link"), url)
    t("projects.topbar.info.edit_all", :link => link).html_safe
  end

  def link_to_project(project, text = project.name)
    link_to text, project_path(project)
  end

  def link_to_branch(branch)
    project = branch.project
    link_to truncate(branch.name), project_path(project, branch.name)
  end

  def link_to_revision(revision)
    branch = revision.branch
    project = branch.project
    link_to revision.uid[0..7], project_path(project, branch.name, revision.uid)
  end

  def link_to_subnavi(action, path, i18n_opts = {})
    text = t("projects.subnavi.#{action}", i18n_opts)
    classes = %w(btn btn-default)
    classes << 'active' if controller.action_name == action.to_s
    link_to text.html_safe, path, :class => classes
  end

  def link_to_with_hostname(url, options)
    hostname = URI.parse(url).host.gsub(/^www\./, '')
    link_to hostname, url, options
  end

  def promo_hint
    <<-PROMO
    <!--
Hi there,

I want to propose to add this badge to the README to show off inline-documentation: [![Inline docs](http://inch-ci.org/github/#{@project.name}.svg)](http://inch-ci.org/github/#{@project.name})

The badge links to [Inch CI](http://inch-ci.org) and shows an evaluation by [InchJS](http://trivelop.de/inchjs), a project that tries to raise the visibility of inline-docs. Besides testing and other coverage, documenting your code is often neglected although it is a very engaging part of Open Source.

So far over 500 **Ruby** projects are sporting these badges to raise awareness for the importance of inline-docs and to show potential contributors that they can expect a certain level of code documentation when they dive into your project's code and motivate them to eventually document their own. I would really like to do the same for the **JavaScript** community and roll out support for JS over the coming weeks (early adopters are [forever](https://github.com/foreverjs/forever), [node-sass](https://github.com/sass/node-sass) and [when](https://github.com/cujojs/when)).

Although this is "only" a passion project, I really would like to hear your thoughts, critique and suggestions. Your status page is http://inch-ci.org/github/#{@project.name}

What do you think?
    -->
    PROMO
  end

  def show_rebuild_link?
    @project.build_on_inch_ci?
  end
end

app/views/projects/_badge_selector.html.haml
- image_format = BadgeMarkup::DEFAULT_IMAGE_FORMAT

#badge-image-markup{:style => "display: none;"}
  .row.row-badge-selector
    .container
      %form
        %p= t('badge.choose_hint').html_safe
        - badge_markup.styles.each_with_index do |style, index|
          %label
            %input{:type => 'radio', :name => 'badge-format', :checked => index == 0 ? :checked : nil, :"data-select-badge-format" => style || 'default'}
              = image_tag badge_markup.image_path(image_format, style), :"data-toggle" => 'tooltip', :title => t("badge.image_style.#{style || 'default'}")
        .clearfix

      - badge_markup.styles.each_with_index do |style, index|
        .badge-image-markup{:class => "badge-image-markup-#{style || 'default'}", :style => index == 0 ? nil : "display: none;"}
          - badge_markup.each(image_format, style) do |markup_format, string|
            %p
              %label= t("badge.markup_format.#{markup_format}")
              %input{:value => string, :type => "text", :class => "url", :"data-select-on-click" => true}

app/views/projects/_form_edit.html.haml
= form_for(@project, :method => :put, :html => {:class => 'edit-project-form form-horizontal'}) do |f|
  .form-group{:class => flash[:error] ? 'has-error' : nil}
    = f.label(:language, t(".label.language"))
    = f.select(:language, InchCI::Config::LANGUAGES, {}, :class => "form-control")
  .form-group{:class => flash[:error] ? 'has-error' : nil}
    = f.label(:language, t(".label.documentation_url"))
    = f.text_field(:documentation_url, :class => "form-control")

  .form-group{:class => flash[:error] ? 'has-error' : nil}
    = submit_tag t(".submit"), :class => "btn btn-success"

    - flash[:error].tap do |error_message|
      .error
        = error_message

app/views/projects/_history_build_template.html.haml
.history-build-wrapper{:"data-build-id" => "{{build_id}}"}
  %table.table.table-striped.history
    %tbody
      %tr
        %td.status{:class => "status {{build_status}}"}
          = "#" + "{{build_number}}"
        %td.revision_uid
          Created new build ...
        %td.duration{:colspan => 2}

app/views/projects/_history_revision_diff.html.haml
.revision_diff
  /
    .pull-left
      %span.badge= revision_diff.revision.uid
      = revision_diff.revision.message
    .pull-right
      - revision_diff.changes.each do |key, list|
        - if list.size > 0
          = list.size
          = key

  %table.table.table-striped.grade-list-table
    - negative_priority_count = 0

    - list = revision_diff.changes['degraded']
    - if list.size > 0
      - list.each do |code_object_diff|
        - code_object = @code_object_map[code_object_diff.after_object_id]
        - before_code_object = @code_object_map[code_object_diff.before_object_id]
        %tr.degraded
          %td.change
            = icon(:bug)
          %td.grade
            .grade-circle{:class => "grade-circle-#{code_object.grade}", :title => t("grade_list_table.grade_icon_hint")}
              = code_object.grade
          %td.fullname
            = code_object.fullname
            %b has gotten worse
            (was #{before_code_object.grade})
          %td.priority
            = image_tag "priority/#{code_object.priority_symbol}.png", :title => t("grade_list_table.priority_icon_hint")

    - list = revision_diff.changes['improved']
    - if list.size > 0
      - list.each do |code_object_diff|
        - code_object = @code_object_map[code_object_diff.after_object_id]
        - before_code_object = @code_object_map[code_object_diff.before_object_id]
        %tr.improved
          %td.change
            = icon(:"smile-o")
          %td.grade
            .grade-circle{:class => "grade-circle-#{code_object.grade}", :title => t("grade_list_table.grade_icon_hint")}
              = code_object.grade
          %td.fullname
            = code_object.fullname
            %b has improved
            (was #{before_code_object.grade})
          %td.priority
            = image_tag "priority/#{code_object.priority_symbol}.png", :title => t("grade_list_table.priority_icon_hint")

    - list = revision_diff.changes['added']
    - if list.size > 0
      - list.each do |code_object_diff|
        - code_object = @code_object_map[code_object_diff.after_object_id]
        - negative_priority_count += 1 if code_object.priority < 0
        %tr.added{:"data-negative-priority" => code_object.priority < 0 ? revision_diff.id : nil, :style => code_object.priority < 0 ? "display: none" : nil}
          %td.change
            = icon(:plus)
          %td.grade
            .grade-circle{:class => "grade-circle-#{code_object.grade}", :title => t("grade_list_table.grade_icon_hint")}
              = code_object.grade
          %td.fullname
            = code_object.fullname
          %td.priority
            = image_tag "priority/#{code_object.priority_symbol}.png", :title => t("grade_list_table.priority_icon_hint")

    - if negative_priority_count > 0
      %tr.show_negative_priority
        %td{:colspan => 4}
          %a{:href => "#", :"data-show-negative-priority" => revision_diff.id}
            - if negative_priority_count == 1
              Show #{negative_priority_count} low priority object ...
            - else
              Show #{negative_priority_count} low priority objects ...

app/views/projects/_page.html.haml
- content_for(:subheader) do
  = render "topbar"

- if @revision
  = render "badge_selector"

- if @revision || @pending_build
  .row.row-subsubheader
    .container
      - if @pending_build
        = render "stats_pending_build", :build => @pending_build
      - else
        = render "stats"
      = yield(:after_stats)

.row.row-content
  .container
    - if @revision
      = render "subnavi"

      - if @pending_build
        = render "wait_for_build", :build => @pending_build
      - else
        = yield

    - else

      - if @pending_build
        = render "wait_for_build", :build => @pending_build
      - else
        - if @project.build_on_travis?
          .repo-info
            .how_to_travis
              - if @project.language?(:elixir)
                = render "shared/how_to_travis_elixir"
        - else
          - if @project.language?(:javascript) && @project.last_build.no_sources_found?
            .repo-info
              .explanation
                = markdown t("projects.start_build.javascript_sources_not_found")
          - else
            %p.start_build
              %em= t('projects.start_build.info')
              = icon('level-up')

app/views/projects/_show_grade_list.html.haml
- show_count ||= 5

- grade_list.code_objects[show_count..-1].each do |code_object|
  %tr
    = render "shared/grade_list_cells", :grade_list => grade_list, :code_object => code_object

app/views/projects/_stats.html.haml
.stats-wrapper
  .stats
    .progress
      .progress-bar.progress-bar-A{:"data-placement" => 'bottom', :"data-toggle" => 'tooltip', :style => "width: #{@collection.percent('A')}%", :title => t('grade_list_table.header_A')}
      .progress-bar.progress-bar-B{:"data-placement" => 'bottom', :"data-toggle" => 'tooltip', :style => "width: #{@collection.percent('B')}%", :title => t('grade_list_table.header_B')}
      .progress-bar.progress-bar-C{:"data-placement" => 'bottom', :"data-toggle" => 'tooltip', :style => "width: #{@collection.percent('C')}%", :title => t('grade_list_table.header_C')}
      .progress-bar.progress-bar-U{:"data-placement" => 'bottom', :"data-toggle" => 'tooltip', :style => "width: #{@collection.percent('U')}%", :title => t('grade_list_table.header_U')}

    .row
      .col-sm-3.build_number
        %span.text-muted= icon(:server, :title => t('projects.topbar.info.build_number'))

        - if @revision && @build = @revision.builds.last
          = "##{@build.number}"
          %small
            = link_to_build_history(@project)

      .col-sm-3.language
        %span.text-muted= icon(:"quote-right", :title => t('projects.topbar.info.language'))

        = @project.language || t('projects.topbar.info.language_unknown')
        - if !logged_in? || (logged_in? && can_edit?)
          %small
            = link_to_edit_project(@project)

      - if @build.finished_at

        .col-sm-3.duration
          %span.text-muted= icon(:"clock-o", :title => t('projects.topbar.info.duration'))

          = (@build.finished_at - @build.started_at).to_i
          seconds

        .col-sm-3.finished_ago
          %span.text-muted= icon(:"calendar", :title => t('projects.topbar.info.finished_ago'))

          = t("builds.index.finished_ago", :time_ago => time_ago_in_words(@build.finished_at))

      - elsif @build.started_at
        .col-sm-3.duration
          %span.text-muted= icon(:"clock-o", :title => t('projects.topbar.info.finished_at'))

          started
          %span{"data-increment-every-second" => true}
            = (Time.now - build.started_at).to_i
          seconds ago

app/views/projects/_stats_pending_build.html.haml
.stats-wrapper
  .stats
    .progress.progress-striped.active
      .progress-bar.progress-bar-U{:style => "width: 100%"}

    .row
      .col-sm-3.build_number
        %span.text-muted= icon(:server, :title => t('projects.topbar.info.build_number'))

        = "##{build.number}"
        %small
          = link_to_build_history(@project)

      .col-sm-3.language
        %span.text-muted= icon(:"quote-right", :title => t('projects.topbar.info.language'))

        = @project.language
        - if !logged_in? || (logged_in? && can_edit?)
          %small
            = link_to_edit_project(@project)

      - if build.finished_at

        .col-sm-3.duration
          %span.text-muted= icon(:"clock-o", :title => t('projects.topbar.info.duration'))

          = (build.finished_at - build.started_at).to_i
          seconds

        .col-sm-3.finished_ago
          %span.text-muted= icon(:"calendar", :title => t('projects.topbar.info.finished_ago'))

          = t("builds.index.finished_ago", :time_ago => time_ago_in_words(build.finished_at))

      - elsif build.started_at
        .col-sm-3.duration
          %span.text-muted= icon(:"clock-o", :title => t('projects.topbar.info.duration'))

          started
          %span{"data-increment-every-second" => true}
            = (Time.now - build.started_at).to_i
          seconds ago

        .col-sm-3.status
          %span.text-muted= icon(:"info", :title => t('projects.topbar.info.status'))

          = build.status
      - else

        .col-sm-3.duration
          %span.text-muted= icon(:"clock-o", :title => t('projects.topbar.info.duration'))

          = '-'

        .col-sm-3.finished_ago
          %span.text-muted= icon(:"info", :title => t('projects.topbar.info.finished_ago'))

          = '-'

app/views/projects/_webhook_hint.html.haml
- if params[:pending_build]
  .configure-a-webhook
    %em Pro-Tip:
    You can also
    = link_to "configure a webhook!", can_edit? ? user_path(current_user) : help_webhook_path
    = icon('hand-o-left')

app/views/projects/history.html.haml
= render :layout => "page" do
  .repo-info
    .explanation
      %p
        Here you can see the
        %strong build history
        of your project.
      %p
        In case the documentation changed, it is shown here.

    .history-builds.table-responsive
      - not_rendered_builds = []
      - @builds.each_with_index do |build, index|
        - rev_diff = build.revision_diff
        - no_changes_present = rev_diff && rev_diff.change_count == 0
        - if index > 0 && (build.duplicate? || no_changes_present)
          - not_rendered_builds << build
        - else
          - if not_rendered_builds.size > 0
            = render "history_no_changes_builds", :builds => not_rendered_builds
            - not_rendered_builds = []
          = render "history_build", :build => build

.inch-links
  %b Everything Inch CI
  %ul.list-unstyled
    %li= link_to "Get your own badge!", root_path
    %li= link_to "Configure a webhook for continuous integration!", help_webhook_path
    %li= link_to "Raising the visibility of inline-docs", "http://trivelop.de/2014/02/24/visibility-of-documentation/"
    %li= link_to "Why Inch doesn't use percentages", "http://trivelop.de/2014/02/17/why-inch-doesnot-use-percentages/"
    %li= link_to "Inch project page", "http://trivelop.de/inch"

.row.row-prefooter
  .container
    = render "about_footer"

:javascript

  I.gossip.onNewBuild = function onNewBuild(payload) {
    var template = '#{escape_javascript render('history_build_template')}';
    var html = template.replace('{{build_id}}', payload.build_id)
                        .replace('{{build_number}}', '#'+payload.build_number)
                        .replace('{{build_status}}', payload.build_status);
    $('.history-builds').prepend(html);
    updateRemotely(payload.build_id);
  }

  I.gossip.onUpdateBuild = function onUpdateBuild(payload) {
    updateRemotely(payload.build_id);
  }

  function updateRemotely(build_id) {
    var url = "/builds/"+build_id+"/history_show.js";
    jQuery.ajax(url);
  }

app/views/projects/page.js.erb
jQuery('#projects_page').html('<%= escape_javascript render(action_name) %>');

app/views/projects/show.html.haml
#projects_page= render 'show'

= promo_hint.html_safe

app/views/projects/show.js.erb
<% if grade = params[:grade_list] %>
  jQuery('#projects_page tr[data-insert-<%= grade %>]')
    .after('<%= escape_javascript render("show_grade_list", :grade_list => @collection[grade]) %>')
    .remove();
<% else %>
  jQuery('#projects_page').html('<%= escape_javascript render(action_name) %>');
  jQuery('.topbar').html('<%= escape_javascript render('topbar') %>');
<% end %>

app/views/projects/suggestions.html.haml
= render :layout => "page" do
  .repo-info
    .explanation
      %p
        Here are some
        %strong suggestions
        where the project's documentation can be improved:

    .table-responsive
      - @suggestions.each do |grade_list|
        = render "shared/grade_list_table", :grade_list => grade_list, :hide_empty => true, :show_count => 99999

    /
      %p
        You might want to look at these files:
      %ul
        - @files.each do |filename|
          %li= link_to filename, url_on_github(filename), :target => '_blank'
      %hr

.row.row-prefooter
  .container
    = render "about_footer"