config/routes.rb
require 'sidekiq/web'

InchCI::Application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout

  namespace :api do
    get 'v1/cli' => 'cli#hint'
    post 'v1/cli' => 'cli#run'

    get 'v1/builds' => 'builds#hint'
    post 'v1/builds' => 'builds#run'

    get 'v2/builds' => 'builds#hint'
    post 'v2/builds' => 'builds#run'
  end

  # Help section
  get 'learn_more' => 'help#about', :as => :about
  get 'help' => 'help#index', :as => :help
  get 'lets_do_javascript' => 'help#javascript_beta', :as => :lets_do_javascript

  get 'help/webhook' => 'help#webhook', :as => :help_webhook
  get 'help/badge' => 'help#badge', :as => :help_badge
  get 'help/grades' => 'help#grades', :as => :help_grades
  get 'help/config_file_yaml' => 'help#config_file_yaml', :as => :help_configuration_yaml
  get 'help/config_file_json' => 'help#config_file_json', :as => :help_configuration_json

  # legacy URLs
  get 'howto/webhook' => 'help#webhook'
  get 'howto/config_file_yaml' => 'help#config_file_yaml'
  get 'howto/config_file_json' => 'help#config_file_json'

  root 'page#welcome'

  namespace :admin do
    get 'overview' => 'overview#index'
    get 'cli' => 'cli#index'
    get 'badges/added' => 'badges#added'
    get 'badges/in_readme' => 'badges#in_readme'

    resources :builds
    resources :projects
    resources :statistics do
      collection do
        get 'added_badges', :as => :added_badges
        get 'days', :as => :daily
        get 'weeks', :as => :weekly
        get 'months', :as => :monthly
      end
    end
    resources :users
  end

  duo    = ':service/:user'
  triple = ':service/:user/:repo'
  triple_constraints = {:service => /(github)/, :repo => /[^\/]+/}
  badge_constraints = {:format => /(png|svg)/}.merge(triple_constraints)
  json_constraints = {:format => /json/}.merge(triple_constraints)

  get "#{duo}" => 'users#show', :format => false
  post "init_projects" => 'users#init_projects', :as => :init_projects
  post "sync_projects" => 'users#sync_projects', :as => :sync_projects
  get "welcome" => 'users#welcome', :as => :welcome

  get "#{triple}/revision/:revision/code_object/:code_object" => 'code_objects#show', :constraints => triple_constraints

  get "#{triple}.:format" => 'projects#badge', :constraints => badge_constraints
  get "#{triple}.:format" => 'projects#show', :constraints => json_constraints

  get "(#{triple})/builds" => 'builds#index', :as => :builds, :constraints => triple_constraints
  #get "#{triple}(/revision/:revision)/list" => 'projects#show', :constraints => triple_constraints
  get "#{triple}(/revision/:revision)/suggestions" => 'projects#suggestions', :constraints => triple_constraints
  get "#{triple}(/revision/:revision)/history" => 'projects#history', :constraints => triple_constraints
  get "#{triple}(/revision/:revision)" => 'projects#show', :constraints => triple_constraints, :format => false

  post "#{triple}/rebuild" => 'projects#rebuild', :constraints => triple_constraints
  post "#{triple}/update_info" => 'projects#update_info', :constraints => triple_constraints
  post "#{triple}/create_hook" => 'projects#create_hook', :constraints => triple_constraints
  post "#{triple}/remove_hook" => 'projects#remove_hook', :constraints => triple_constraints

  get  "#{triple}/edit" => 'projects#edit', :constraints => triple_constraints
  put  "#{triple}" => 'projects#update', :constraints => triple_constraints

  post 'rebuild' => 'projects#rebuild_via_hook'

  resources :builds do
    member do
      get :history_show
    end
  end
  resources :projects

end

app/models/build.rb
class Build < ActiveRecord::Base
  has_one :project, :through => :branch
  belongs_to :branch
  belongs_to :revision
  has_one :revision_diff, :primary_key => "revision_id", :foreign_key => "after_revision_id"

  validates :branch, :presence => true
  validates :status, :presence => true
end

app/controllers/admin/builds_controller.rb
require 'inch_ci/controller'

class Admin::BuildsController < ApplicationController
  include InchCI::Controller

  layout 'admin'

  PER_PAGE = 200
  def index
    set_builds
    @languages = %w(Elixir JavaScript Ruby)
    @gossip_room = "projects:lobby"
  end

  def show
    view = Action::Build::Show.new(params, load_dump: true)
    expose view
  end

  private

  def set_builds
    @builds = find_builds.map do |build|
        BuildPresenter.new(build)
      end
    @scheduled_builds = @builds.select { |b| b.status == 'created' }
    @running_builds = @builds.select { |b| b.status == 'running' }
    @completed_builds = @builds.select { |b| !%w(created running).include?(b.status) }
  end

  def filter_collection(arel)
    arel = arel.references(:branch).joins(:project)
    if params[:language].present?
      arel = arel.where('LOWER(projects.language) = ?', params[:language].to_s.downcase)
    end
    if params[:statuses].present?
      @statuses = params[:statuses]
      arel = arel.where(:status => @statuses)
    end
    if params[:triggers].present?
      @triggers = params[:triggers]
      arel = arel.where(:trigger => @triggers)
    end
    if uid = params[:uid].presence
      arel = arel.where('projects.uid LIKE ?', "%#{uid}%")
    end
    if params[:service]
      arel = filter_by_service_and_user(arel, params[:service], params[:user], params[:repo])
    end
    arel
  end

  def filter_by_service_and_user(arel, service, user_name, repo_name)
    like = "#{service}:"
    if user_name
      like << "#{user_name}/"
    end
    if repo_name
      like << "#{repo_name}"
    end
    arel.where('projects.uid LIKE ?', like+'%')
  end

  def find_builds
    arel = filter_collection(Build).order('created_at DESC')
    @builds_total_count = arel.count
    arel.limit(PER_PAGE)
  end
end

app/controllers/api/builds_controller.rb
require 'inch'
require 'fileutils'
require 'inch_ci/worker/project/build_json'

module Api
  class BuildsController < ApplicationController
    protect_from_forgery with: :null_session

    def hint
      render_text "> Greetings, Professor Falken.\n\n> _\n"
    end

    def run
      # let's ensure backwards compatibility
      params[:language] = 'javascript' if params[:language] == 'nodejs'

      if valid_params?
        file = dump_request_to_file
        if build = enqueue_build(file.path)
          copy_file(file, build)
          update_project_if_necessary(build.project)

          render_text "Successfully created build ##{build.number}\n" \
                    "URL: #{project_url(build.project)}\n"
        else
          render_text "[ERROR] Build could not be created.\n"
        end
      else
        render_text "[ERROR] #{@param_errors}\n"
      end
    end

    private

    def dump_request_to_file
      write_file filename_with_extension, JSON.pretty_generate(params)
    end

    def enqueue_build(filename)
      InchCI::Worker::Project::BuildJSON.enqueue(filename)
    end

    def filename_for_build(build)
      Rails.root.join('dumps', 'builds', "build-#{build.id}.json")
    end

    def filename_with_extension
      dir = Rails.root.join('dumps', 'builds', language_from_params, Time.now.strftime('%Y%m%d'))
      File.join(dir, request.object_id.to_s + '.json')
    end

    def language_from_params
      params[:language]
    end

    def copy_file(file, build)
      FileUtils.copy file.path, filename_for_build(build)
    end

    def render_text(text)
      render :text => text, :content_type => "text/plain"
    end

    def update_project_if_necessary(project)
      if !project.default_branch # this project is new
        worker = InchCI::Worker::Project::UpdateInfo.new
        worker.perform(project.uid)
      end
    end

    def write_file(filename, contents)
      FileUtils.mkdir_p File.dirname(filename)
      file = File.new(filename, 'w')
      file.write contents
      file.close
      file
    end

    def valid_params?
      if language_from_params.to_s.empty?
        @param_errors = "No language defined."
      end
      @param_errors.nil?
    end
  end
end

app/controllers/builds_controller.rb
require 'inch_ci/controller'

class BuildsController < ApplicationController
  include InchCI::Controller

  layout 'application'

  def index
    view = Action::BuildHistory.new(params)
    expose view
  end

  def history_show
    view = Action::Build::Show.new(params, load_diff: true)
    expose view
  end

  def show
    view = Action::Build::Show.new(params)
    expose view
    render :json => @build
  end
end

app/helpers/builds_helper.rb
module BuildsHelper
  def back_button(path)
    link_to icon('arrow-left') + ' ' + t("shared.back_link"), path, :class => "btn btn-default btn-cancel"
  end

  def build_css_class(build)
    {
      'created' => '',
      'running' => :info,
      'success' => :success,
      'duplicate' => :warning,
      'cancelled' => :cancelled,
    }[build.status] || :danger
  end

  def build_status_icon(build)
    key = build_status_icon_map[build.status]
    title = t("builds.status.#{build.status}", :default => build.status)
    icon(key || :question, :title => title)
  end

  def build_status_icon_map
    {
      'created' => :"circle-o",
      'cancelled' => :"arrow-up",
      'duplicate' => :"check-square",
      'running' => :"spinner fa-pulse",
      'success' => :check,
      'failed:retriever' => :exclamation,
    }
  end

  def build_trigger_icon(build)
    key = build_trigger_icon_map[build.trigger]
    icon(key || :question, :title => build.trigger)
  end

  def build_trigger_icon_map
    {
      'cron' => :"clock-o",
      'hook' => :git,
      'manual' => :user,
      'tag_build' => :tags,
      'shell' => :terminal,
      'travis' => :"cloud-upload",
    }
  end
end

app/views/admin/builds/_index.html.haml
.row
  .col-lg-10
    - unless @scheduled_builds.empty?
      .widget
        .widget-title
          = icon :calculator
          = t("builds.index.scheduled_header", :count => @scheduled_builds.size).html_safe
      .widget-body.medium.no-padding
        = render "table", :builds => @scheduled_builds

    - unless @running_builds.empty?
      .widget
        .widget-title
          = icon :calculator
          = t("builds.index.running_header", :count => @running_builds.size).html_safe
        .widget-body.medium.no-padding
          = render "table", :builds => @running_builds

    - unless @completed_builds.empty?
      .widget
        .widget-title
          = icon :calculator
          = t("builds.index.completed_header")

          .pull-right
      .widget-body.medium.no-padding
        = render "table", :builds => @completed_builds

  .col-lg-2
    .widget
      .widget-title
        = icon :filter
        Filters

      .widget-body
        = form_tag(params, :method => :get) do
          .form-group
            = label_tag :language, "Language"
            = select_tag(:language, options_for_select(['', *@languages], params[:language]), :class => 'form-control')

          .form-group
            %label Status
            %br
            - build_status_icon_map.keys.each do |status|
              %label
                = check_box_tag "statuses[]", status, @statuses ? @statuses.include?(status) : false
                = icon(build_status_icon_map[status], :title => status)

          .form-group
            %label Trigger
            %br
            - build_trigger_icon_map.keys.each do |trigger|
              %label
                = check_box_tag "triggers[]", trigger, @triggers ? @triggers.include?(trigger) : false
                = icon(build_trigger_icon_map[trigger], :title => trigger)

          = submit_tag "Show Builds"
          - if params.size > 2
            or
            = link_to "clear filters", admin_builds_path

      .widget-title
        = icon :search
        Search

      .widget-body
        = form_tag(params, :method => :get) do
          .form-group
            = text_field_tag :uid, params[:uid], :class => 'form-control'

          = submit_tag "Search"

      .widget-title
        Displaying
        = @builds.size
        = "/"
        = @builds_total_count
        builds.

app/views/admin/builds/_table.html.haml
.table-responsive
  %table.table.table-striped.builds
    %thead
      %tr
        %th #
        %th Project
        %th Builds
        %th Language
        %th.revision_uid Revision
        %th.duration Duration
        %th.finished_at Finished
        %th.status{:colspan => 2} Status
        %th
    %tbody
      - builds.each do |build|
        - project = build.branch.project
        %tr{:"data-build-trigger" => build.trigger}
          %td= link_to build.id, admin_build_path(build.id)
          %td= link_to_project project
          %td= link_to icon(:signal), :service => project.service_name, :user => project.user_name, :repo => project.repo_name
          %td= link_to project.language, :language => project.language
          %td.revision_uid
            - if revision = build.revision
              - if revision.tag_uid
                - if revision.tag_uid.size < 10
                  %span.badge{:title => revision.uid}= revision.tag_uid
                - else
                  %span.badge{:title => revision.tag_uid(false)}= revision.tag_uid
              - else
                = revision.uid
          - if build.finished_at
            %td.duration
              = (build.finished_at - build.started_at).to_i
              seconds
            %td.finished_at
              = t("builds.index.finished_ago", :time_ago => time_ago_in_words(build.finished_at))
          - elsif build.started_at
            %td.duration{:colspan => 2}
              started
              %span{"data-increment-every-second" => true}
                = (Time.now - build.started_at).to_i
              seconds ago
          - else
            %td.duration{:colspan => 2}
          %td.status{:class => build_css_class(build)}
            = build_status_icon(build)
          %td.trigger
            = build_trigger_icon(build)
          %td.text-right
            = link_to icon(:refresh), project_rebuild_path(project), :method => :post

app/views/admin/builds/index.html.haml
#builds_index= render "index"

:javascript
  I.wait_for_build.initReload('#{url_for(params.merge(:format => :js))}');

app/views/admin/builds/show.html.haml
.row
  .col-lg-6
    .widget
      .widget-title
        = icon :calculator
        = "Build ##{@build.id}"
    .widget-body.medium.no-padding
      .table-responsive
        %table.table.table-striped.build
          %tbody
            - project = @build.branch.project
            %tr
              %th #
              %td= link_to @build.id, admin_build_path(@build.id)
            %tr
              %th Builds
              %td= link_to icon(:signal), admin_builds_path(:service => project.service_name, :user => project.user_name, :repo => project.repo_name)
            %tr
              %th.revision_uid Revision
              %td.revision_uid
                - if revision = @build.revision
                  - if revision.tag_uid
                    - if revision.tag_uid.size < 10
                      %span.badge{:title => revision.uid}= revision.tag_uid
                    - else
                      %span.badge{:title => revision.tag_uid(false)}= revision.tag_uid
                  - else
                    = revision.uid
            %tr
              %th.duration Duration
              %td.duration
                - if @build.finished_at
                  = (@build.finished_at - @build.started_at).to_i
                  seconds
                - elsif @build.started_at
                  started
                  %span{"data-increment-every-second" => true}
                    = (Time.now - @build.started_at).to_i
                  seconds ago
            %tr
              %th.finished_at Finished
              %td.finished_at
                - if @build.finished_at
                  = t("builds.index.finished_ago", :time_ago => time_ago_in_words(@build.finished_at))
            %tr
              %th.status Trigger
              %td.trigger
                = build_trigger_icon(@build)
                = @build.trigger
            %tr
              %th.finished_at Status
              %td.status{:class => build_css_class(@build)}
                = build_status_icon(@build)
                = @build.status
            - if @build.stderr.present?
              %tr
                %th.finished_at stderr
                %td.terminal
                  - @build.stderr.lines.each do |line|
                    = line
                    %br

    = render "admin/projects/project", :project => @build.branch.project


  .col-lg-6
    .widget
      .widget-title
        = icon :terminal
        Request

      .table-responsive
        - if @dump
          .terminal
            - @dump.lines.each do |line|
              = line
              %br